### ISSUE TITLE
Real time data apis

### ISSUE THREAD

**Issue by gowtham06** [airavata-courses/autobots#13]
Investigate on any real time data apis that are available for free.  We can use this api for real time data streaming/message queues for the assignment 1
Some of the APIs that we can consider are -
- [ ] Twitter
- [ ] OpenNasa API
- [ ] Weather API

These are some of my considerations.

@naveenkumarmarri  If you find anything new, include it here so that we can keep track of it.

**Comment by naveenkumarmarri** [comment]
@gowtham06 I already opened an issue for this see issue #4 

Closing this issue
