### ISSUE TITLE
Node_Modules In Develop branch

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#29]
As per my knowledge, you are not supposed to check-in **node_modules**, Could you please explain why have you checked-in node modules.

**Comment by naveenkumarmarri** [comment]
@DGRamya Yes, I think we added in the .gitignore file but some how they got checked in.
Will look into it.

**Comment by gowtham06** [comment]
@DGRamya  Thanks for the update. As @naveenkumarmarri mentioned we added the folder in .gitignore file, but somehow it got pushed to the develop branch. But now I removed the node_modules file and pushed the code. Now it should be fine. Again thanks for the update.

**Comment by DGRamya** [comment]
Looks fine now. Thank you
