### ISSUE TITLE
Error in NPM start

### ISSUE THREAD

**Issue by shivteja14** [airavata-courses/autobots#36]
npm start

> streaming@1.0.0 start /home/shayyag/Desktop/autobots/autobots/ui
> node app.js

Express server listening on port:5000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND broker broker:9092
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streaming@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streaming@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shayyag/.npm/_logs/2018-09-25T23_58_47_035Z-debug.log

Could you look at this error?

**Comment by naveenkumarmarri** [comment]
@shivteja14 

Did you add the host alias entries in `/etc/hosts` file mentioned in [Installation guide](https://github.com/airavata-courses/autobots/wiki/Installation#creating-topic)

**Comment by shivteja14** [comment]
Oh sorry, I missed those. Its working now thanks @naveenkumarmarri
