### ISSUE TITLE
Update the architecture diagram and project goals for assignment 2

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#54]

**Comment by gowtham06** [comment]
Working on it now. Will update the wiki page soon

**Comment by naveenkumarmarri** [comment]
@DGRamya you can find the problem statement and the architecture on [wiki](https://github.com/airavata-courses/autobots/wiki/Project-2)

**Comment by DGRamya** [comment]
It would have been helpful for testing if updated early.
