### ISSUE TITLE
file failed to upload

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#57]
Type of file: Serialized file with 2,590 bytes (4 KB on disk).

Chunk size 40: 
upload file -> pause -> resume 

throws the error in snapshot

![image](https://user-images.githubusercontent.com/26709753/47418732-b6d79900-d748-11e8-8d7a-96ecbdbaab50.png)

**Comment by DGRamya** [comment]
I also tried uploading pdf file chunk size as 500 even then I am getting same error, is there any step which I am missing?

**Comment by naveenkumarmarri** [comment]
Can you try now?

**Comment by DGRamya** [comment]
tested for pdf  and text files, works fine.
