### ISSUE TITLE
File Failed to download

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#58]
I was able to upload the file successfully and the download button popped up, but when I clicked on download file, it redirect to another page throwing "Not found error"

**Comment by naveenkumarmarri** [comment]
Hi


That is how it is implemented so far. May be in future assignments, we will
build on top of it.

Regards
Naveen

**Comment by gowtham06** [comment]
@DGRamya  thanks for noticing. Actually we have a download service running. But there are some issues with that, we are trying to resolve it. Will update once done.

**Comment by DGRamya** [comment]
@naveenkumarmarri , so, the download option is not available for this milestone right?

**Comment by naveenkumarmarri** [comment]
I think given the timeline for peer review, it is fair to consider for next
milestone

**Comment by DGRamya** [comment]
Okay

**Comment by naveenkumarmarri** [comment]
@DGRamya I'm able to access it and upload files. What error are you getting?

**Comment by DGRamya** [comment]
@naveenkumarmarri Please provide the project goals, so that I can close the issues.

**Comment by DGRamya** [comment]
@naveenkumarmarri  what are the types of files we can upload, is it only text files ?

**Comment by naveenkumarmarri** [comment]
> @naveenkumarmarri what are the types of files we can upload, is it only text files ?

Sure, you can try with almost all file formats, it worked for me. Let us know if you face issues with any particular file format.

**Comment by gowtham06** [comment]
@DGRamya  Download is working now when you try it locally. However for some reasons, download is not working in jetstream. There might be an issue with the file path of the uploaded files in the Tus server. Working on it. Will keep you updated.

**Comment by gowtham06** [comment]
> @naveenkumarmarri what are the types of files we can upload, is it only text files ?
To answer this, the files are hashed and stored accordingly in the destination. This is done to keeping in mind  that file upload should be resumed based on this hash value. So its up to our implementation of tus-client on maintaining the file type/ name etc.

**Comment by naveenkumarmarri** [comment]
> @naveenkumarmarri Please provide the project goals, so that I can close the issues, also please update the architecture diagram and overview of implementation details

Added the details on [wiki](https://github.com/airavata-courses/autobots/wiki/Project-2)

**Comment by gowtham06** [comment]
Closing the issue since its now resolved.
