### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#72]
I remember through PPT slides, you had mentioned, "if we pause upload, refresh , we will be able to continue upload," is this scenario valid for testing?

or refresh should not be done after pausing the application.

**Comment by naveenkumarmarri** [comment]
Sure. You can do it. However since It is a stateful service and we are
using a load balancer which might redirected to different node in the
cluster.
We didn't handle state so far. So you might get sporadic results
