### ISSUE TITLE
File upload halts 

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#73]
I tried to upload video file, after the upload reaches middle of the progress, the pause button is changed to "start", and the upload progress starts to continue

**Comment by gowtham06** [comment]
Can you explain the situation in detail?. I tried now. Its working as it is supposed to

**Comment by DGRamya** [comment]
Chunk size 500
File type : small screen record video file
select file and upload
after the file is uploaded half the way, the upload process halts and the "pause" button changes to "start "
<img width="1156" alt="screen shot 2018-11-14 at 9 07 21 pm" src="https://user-images.githubusercontent.com/26709753/48525286-95eafb00-e851-11e8-811d-fe2f510f4363.png">
button

**Comment by naveenkumarmarri** [comment]
@DGRamya Can you retry without entering anything in `Chunk size` field?

**Comment by DGRamya** [comment]
Can you try with video file

**Comment by DGRamya** [comment]
I tried with video file again, it works. May be some sporadic issue.
