### ISSUE TITLE
Upon upload completion, download redirects to page error

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#75]
Once the file upload completes, the file is listed to be downloaded, once i click the download button, the file downloads successfully but the page is redirected to error, is this expected?
<img width="1045" alt="screen shot 2018-11-14 at 9 15 19 pm" src="https://user-images.githubusercontent.com/26709753/48525511-6f798f80-e852-11e8-97b2-3d3b38fda806.png">

**Comment by naveenkumarmarri** [comment]
Yes, the purpose of that service is just to download.

**Comment by DGRamya** [comment]
Okay, If possible remove the error page.
