### ISSUE TITLE
Error during file upload

### ISSUE THREAD

**Issue by naveenkumarmarri** [airavata-courses/autobots#83]
Steps to reproduce
* upload a file, let it upload partially
* close the tab
* Again choose the same file and try to upload.

Following is the error I'm getting when I follow the above steps

![selection_172](https://user-images.githubusercontent.com/2484004/49675410-938c5300-fa43-11e8-8f6b-0370ff88314d.png)

**Comment by gowtham06** [comment]
@naveenkumarmarri  This seems to be a basic http request error from the client when it is trying to resume the upload using a new http request. Started looking into it.

**Comment by gowtham06** [comment]
@naveenkumarmarri  am not able to reproduce this issue in localhost.  Will have to check with kubernetes layer.

**Comment by naveenkumarmarri** [comment]
![image](https://user-images.githubusercontent.com/2484004/49706649-1a346200-fbf5-11e8-8128-3e616c832d34.png)

When an upload is started to a pod in kubernetes deployment, the tus server is creating a rest endpoint and when you resume the upload.
Looks like the services are stateful and just having a network storage doesn't solve this problem.

**Comment by gowtham06** [comment]
Closing the issue. Resolved in #87
