### ISSUE TITLE
How to execute the results of project 4, client service URL?

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#85]

**Comment by naveenkumarmarri** [comment]
@DGRamya
You can access at http://129.114.16.189:30001
Steps are documented at
https://github.com/airavata-courses/autobots/wiki/CI---CD-on-Jetsream

**Comment by DGRamya** [comment]
Please update the description it still points to assignment 2

**Comment by DGRamya** [comment]
1. uploaded one video file using chunk size 500
2. Paused it and resumed from different Wi-Fi

Works fine. I was able to upload video and download the same content.
