### ISSUE TITLE
Jenkins Credentials

### ISSUE THREAD

**Issue by shivteja14** [airavata-courses/autobots#86]
Could you mail the jenkins credentials to shayyag@iu.edu , @naveenkumarmarri

**Comment by gowtham06** [comment]
@shivteja14  I think the jenkins credentials remains the same as the previous assignment. I think I have already mailed you the jenkins credentials for the previous assignment.

**Comment by shivteja14** [comment]
@gowtham06 Yes I have it, sorry for that.
