### ISSUE TITLE
Continuous refresh of the server, leads to error in Uploading the file

### ISSUE THREAD

**Issue by shivteja14** [airavata-courses/autobots#87]
![image](https://user-images.githubusercontent.com/34051223/49767605-19f49f00-fca7-11e8-9461-fff26e5b48ca.png)

Could you explain the issue? @naveenkumarmarri

**Comment by gowtham06** [comment]
@shivteja14  This is due to some issues with the kubernetes layer. We are trying to solve it, but finding it difficult to resolve. Any suggestions to this will be appreciated.

**Comment by gowtham06** [comment]
@shivteja14  Can you try now? I did a temporary fix by adding the refresh functionality in the uploader client

**Comment by shivteja14** [comment]
@gowtham06  It is working now.
